"""initial_schema

Revision ID: 57d4864b7c9c
Revises:
Create Date: 2026-08-20 04:27:13.999599
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "57d4864b7c9c"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("entity_type", sa.String(length=50), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.String(length=200), nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("before_json", sa.Text(), nullable=True),
        sa.Column("after_json", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_table(
        "modern_trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("vat_mode", sa.String(length=20), nullable=False),
        sa.Column("vat_rate", sa.Numeric(precision=8, scale=6), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_modern_trades_code"), "modern_trades", ["code"], unique=True)
    op.create_table(
        "branch_mappings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("modern_trade_id", sa.Integer(), nullable=False),
        sa.Column("source_branch_code", sa.String(length=30), nullable=False),
        sa.Column("wa_branch_code", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("changed_by", sa.String(length=200), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["modern_trade_id"],
            ["modern_trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_branch_map_lookup",
        "branch_mappings",
        ["modern_trade_id", "source_branch_code", "effective_from"],
        unique=False,
    )
    op.create_table(
        "import_batches",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("modern_trade_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("data_date", sa.Date(), nullable=False),
        sa.Column("source_path", sa.Text(), nullable=False),
        sa.Column("source_filename", sa.String(length=255), nullable=False),
        sa.Column("checksum_sha256", sa.String(length=64), nullable=False),
        sa.Column(
            "discovered_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("store_count", sa.Integer(), nullable=False),
        sa.Column("sku_count", sa.Integer(), nullable=False),
        sa.Column("negative_row_count", sa.Integer(), nullable=False),
        sa.Column("source_amount", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("sales_qty", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("stock_on_hand", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("reported_stock_on_hand", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("stock_on_order", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("reconciliation_errors", sa.Text(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["modern_trade_id"],
            ["modern_trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("modern_trade_id", "checksum_sha256", name="uq_batch_mt_checksum"),
    )
    op.create_index(
        "ix_batch_mt_period", "import_batches", ["modern_trade_id", "data_date"], unique=False
    )
    op.create_index(
        op.f("ix_import_batches_data_date"), "import_batches", ["data_date"], unique=False
    )
    op.create_index(op.f("ix_import_batches_status"), "import_batches", ["status"], unique=False)
    op.create_table(
        "item_mappings",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("modern_trade_id", sa.Integer(), nullable=False),
        sa.Column("source_sku", sa.String(length=50), nullable=False),
        sa.Column("wa_item_code", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("changed_by", sa.String(length=200), nullable=False),
        sa.Column(
            "changed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["modern_trade_id"],
            ["modern_trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_item_map_lookup",
        "item_mappings",
        ["modern_trade_id", "source_sku", "effective_from"],
        unique=False,
    )
    op.create_table(
        "sales_inventory_facts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("batch_id", sa.BigInteger(), nullable=False),
        sa.Column("data_date", sa.Date(), nullable=False),
        sa.Column("source_branch_code", sa.String(length=30), nullable=False),
        sa.Column("source_branch_name", sa.String(length=300), nullable=False),
        sa.Column("category", sa.String(length=30), nullable=True),
        sa.Column("subcategory", sa.String(length=30), nullable=True),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column("source_sku", sa.String(length=50), nullable=False),
        sa.Column("barcode", sa.String(length=50), nullable=True),
        sa.Column("source_description", sa.Text(), nullable=True),
        sa.Column("product_type", sa.String(length=100), nullable=True),
        sa.Column("source_amount", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("amount", sa.Numeric(precision=28, scale=12), nullable=False),
        sa.Column("sales_qty", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("stock_on_hand", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("stock_on_order", sa.Numeric(precision=20, scale=4), nullable=False),
        sa.Column("last_sold_date", sa.Date(), nullable=True),
        sa.Column("last_receive_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(["batch_id"], ["import_batches.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "batch_id", "source_branch_code", "source_sku", name="uq_fact_batch_branch_sku"
        ),
    )
    op.create_index(
        "ix_fact_date_branch",
        "sales_inventory_facts",
        ["data_date", "source_branch_code"],
        unique=False,
    )
    op.create_index(
        "ix_fact_date_sku", "sales_inventory_facts", ["data_date", "source_sku"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fact_date_sku", table_name="sales_inventory_facts")
    op.drop_index("ix_fact_date_branch", table_name="sales_inventory_facts")
    op.drop_table("sales_inventory_facts")
    op.drop_index("ix_item_map_lookup", table_name="item_mappings")
    op.drop_table("item_mappings")
    op.drop_index(op.f("ix_import_batches_status"), table_name="import_batches")
    op.drop_index(op.f("ix_import_batches_data_date"), table_name="import_batches")
    op.drop_index("ix_batch_mt_period", table_name="import_batches")
    op.drop_table("import_batches")
    op.drop_index("ix_branch_map_lookup", table_name="branch_mappings")
    op.drop_table("branch_mappings")
    op.drop_index(op.f("ix_modern_trades_code"), table_name="modern_trades")
    op.drop_table("modern_trades")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
