"""widen_import_status

Revision ID: 60c74273e8ee
Revises: 57d4864b7c9c
Create Date: 2026-08-20 04:44:57.279920
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "60c74273e8ee"
down_revision: str | None = "57d4864b7c9c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "import_batches",
        "status",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "import_batches",
        "status",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
