import { fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { AdGatewayTestPanel } from './AdGatewayTestPanel'

afterEach(() => vi.unstubAllGlobals())
it('tests saved gateway separately, clears password and explains missing MTPulse account', async () => {
  const request = vi.fn().mockResolvedValue({ ok: true, json: async () => ({ gateway_status: 'success', mtpulse_status: 'account_missing', message: 'AD Gateway ยืนยันตัวตนสำเร็จ' }) })
  vi.stubGlobal('fetch', request)
  render(<AdGatewayTestPanel />)
  fireEvent.change(screen.getByLabelText('AD Username'), { target: { value: 'New.Employee' } })
  const password = screen.getByLabelText('AD Password')
  expect(password).toHaveAttribute('type', 'password')
  fireEvent.change(password, { target: { value: 'test-password' } })
  fireEvent.click(screen.getByRole('button', { name: 'แสดงรหัสผ่านทดสอบ AD' }))
  expect(password).toHaveAttribute('type', 'text')
  fireEvent.click(screen.getByRole('button', { name: 'ทดสอบ AD Login' }))
  expect(password).toHaveValue('')
  expect(password).toHaveAttribute('type', 'password')
  expect(await screen.findByText(/ยังไม่มีบัญชีใน MTPulse กรุณาสร้าง/)).toBeInTheDocument()
  expect(request).toHaveBeenCalledWith('/api/settings/ciam-sso/test-ad-login', expect.objectContaining({ method: 'POST', body: JSON.stringify({ username: 'New.Employee', password: 'test-password' }) }))
  expect(request.mock.calls).toHaveLength(1)
})
it('clears credentials after errors and allows another attempt', async () => {
  vi.stubGlobal('fetch', vi.fn().mockRejectedValue(new Error('network unavailable')))
  render(<AdGatewayTestPanel />)
  fireEvent.change(screen.getByLabelText('AD Username'), { target: { value: 'tester' } })
  fireEvent.change(screen.getByLabelText('AD Password'), { target: { value: 'test-password' } })
  fireEvent.click(screen.getByRole('button', { name: 'ทดสอบ AD Login' }))
  expect(await screen.findByRole('alert')).toHaveTextContent('network unavailable')
  expect(screen.getByLabelText('AD Password')).toHaveValue('')
  await waitFor(() => expect(screen.getByLabelText('AD Username')).not.toBeDisabled())
})
it('shows rejection separately from the current admin session', async () => {
  const expired = vi.fn()
  window.addEventListener('mtpulse:unauthorized', expired)
  vi.stubGlobal('fetch', vi.fn().mockResolvedValue({ ok: true, json: async () => ({ gateway_status: 'rejected', mtpulse_status: 'not_checked', message: 'AD ไม่ยืนยันตัวตน' }) }))
  render(<AdGatewayTestPanel />)
  fireEvent.change(screen.getByLabelText('AD Username'), { target: { value: 'tester' } })
  fireEvent.change(screen.getByLabelText('AD Password'), { target: { value: 'incorrect' } })
  fireEvent.click(screen.getByRole('button', { name: 'ทดสอบ AD Login' }))
  expect(await screen.findByText(/AD ไม่ยืนยันตัวตน/)).toBeInTheDocument()
  expect(expired).not.toHaveBeenCalled()
  window.removeEventListener('mtpulse:unauthorized', expired)
})
